### ISSUE TITLE
Stage #1 - Atomic

### ISSUE THREAD

**Issue by ReneKrewinkel** [Markusvdam/educom-runtime-records-1666166020#2]
<ul>
<li>Identifieceer alle Atoms, Molecules, Organisms, (eventueel templates) en Pages.</li>
<li>Leg een spreadsheet of HTML document aan met de "breakdown"</li>
</ul>

**Comment by Markusvdam** [comment]
**ATOMS**
•	Logo
•	Labels
o	Regular text
o	Price label
•	Buttons
o	Read more
o	Add to cart button
o	Checkout button
o	Hamburger menu
o	Delete item (cart)
o	Filter button
o	Save button
•	Icons
o	Mail
o	Discogs
o	Facebook
o	Twitter
o	Instagram
o	Arrow right
•	Text fields
o	Homepage search
o	Checkout field
•	Images
o	Homepage header image
o	Product image
o	Disc image
o	Record store image

**MOLECULES**
•	Featured-item homepage header
•	Record-image-incl-disc
•	Search and filter
•	List items
•	Shopping cart row

**ORGANISMS**
•	Product-page item
•	Product-card
•	Homepage search-block (search + list)
•	Homepage header
•	Shopping cart all
•	Footer
