### ISSUE TITLE
Stage #1 - Payment scherm

### ISSUE THREAD

**Issue by ReneKrewinkel** [Markusvdam/educom-runtime-records-1666166020#6]
<ul>
<li>Design een payment scherm in je design tool</li>
<li>Implementeer het payment scherm in je app</li>
<li>ook hier, voeg een aantal overzichtelijke issues toe in je repo</li>
</ul>

**Comment by Markusvdam** [comment]
Heel minimalistisch geimplementeerd. Werkbaar maar niet mooi. Dit gedaan ivm door willen gaan naar Angular.
